RMS/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RMS.Data;
using RMS.Models;

namespace RMS.Controllers
{
    public class ItemsController : Controller
    {
        private Context db = new Context();

        // GET: Items
        [HttpGet]
        public ActionResult Index()
        {
            return View(db.itemDB.ToList());
        }

        // GET: Items/Details/5
        public ActionResult Details(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.itemDB.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // GET: Items/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Items/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Item item)
        {
            if (ModelState.IsValid)
            {

                string fileName = Path.GetFileNameWithoutExtension(item.imageFile.FileName);
                string extention = Path.GetExtension(item.imageFile.FileName);
                fileName = fileName + DateTime.Now.ToString("yymmssfff")+extention;
                item.itemImage = "~/Image/" + fileName;
                fileName = Path.Combine(Server.MapPath("~/Image/"), fileName);
                item.imageFile.SaveAs(fileName);

                db.itemDB.Add(item);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(item);
        }

        // GET: Items/Edit/5
        public ActionResult Edit(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.itemDB.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // POST: Items/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "itemId,itemName,itemPrice,itemDescription,itemQnt")] Item item)
        {
            if (ModelState.IsValid)
            {
                db.Entry(item).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(item);
        }

        // GET: Items/Delete/5
        public ActionResult Delete(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.itemDB.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // POST: Items/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Item item = db.itemDB.Find(id);
            db.itemDB.Remove(item);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }



    }
}

RMS/Controllers/MainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RMS.Controllers
{
    public class MainController : Controller
    {
        // GET: Main
        public ActionResult Index()
        {


            return View();
        }
    }
}

RMS/Views/Admin/AdminHome.cshtml
@model IEnumerable<RMS.Models.Item>

@{
    ViewBag.Title = "AdminHome";
}




<div style="margin-left:60%;margin-top:-45px;position:absolute">
    <table>
        <tr>
            <td>
                <div style="padding:10px;">
                    @Html.ActionLink("Home", "AdminHome", "Admin","", new { @class = "tx-wht" })
                </div>
            </td>
            <td>
                <div style="padding:10px;">
                    @Html.ActionLink("User Control", "Home", "Admin", "", new { @class = "tx-wht" })
                </div>
            </td>
            <td>
                <div style="padding:10px;">
                    @Html.ActionLink("Item control", "Index", "Items", "", new { @class = "tx-wht" })
                </div>
            </td>

            <td>
                <div class="dropdown">
                    <span style="color:aliceblue">Generate reports</span>
                    <div class="dropdown-content">
                        <p>@Html.ActionLink("List of customers", "ListOfCustomer", "Admin")</p>
                        <p>@Html.ActionLink("List of items", "ListOfItems", "Admin")</p>
                        <p>@Html.ActionLink("List of order", "ListOfOreders", "Admin")</p>

                    </div>
                </div>
            </td>
            <td>
                <div style="padding:10px;">
                    @Html.ActionLink("Log out", "Index", "Main", "", new { @class = "tx-wht" })
                </div>
            </td>
        </tr>
    </table>
</div>

<br />


<div class="row col-md-12" style="margin-top:20px;margin-left:5%">

    @foreach (var item in Model)
    {
        <div class="row col-md-3">
            <div style="width:300px;background-color:rgba(0,0,0,0.5);padding:20px;color:aliceblue">
                <div>
                    <img src="@Url.Content(item.itemImage)"  width="250" height="250"/>
                </div>
                <center>
                    <div>
                        @Html.DisplayFor(modelItem => item.itemName)
                    </div>
                    <div>
                        R.@Html.DisplayFor(modelItem => item.itemPrice)/=
                    </div>
                    <div>
                        @Html.DisplayFor(modelItem => item.itemDescription)
                    </div>
                </center>

                
                <div style="padding:10px;float:right">
                    @Html.ActionLink("Details", "Details", "Items", new { id = item.itemId }, new { @class = "btn btn-success" })
                </div>
            </div>
        </div>

    }
</div>

RMS/Views/Admin/Create.cshtml
@model RMS.Models.User

@{
    ViewBag.Title = "Create";
}

<div style="margin-left:60%;margin-top:-40px;position:absolute">
    <table>
        <tr>
            <td>
                <div style="padding:10px;">
                    @Html.ActionLink("Home", "AdminHome", "Admin", "", new { @class = "tx-wht" })
                </div>
            </td>
            <td>
                <div style="padding:10px;">
                    @Html.ActionLink("User Control", "Home", "Admin", "", new { @class = "tx-wht" })
                </div>
            </td>
            <td>
                <div style="padding:10px;">
                    @Html.ActionLink("Item control", "Index", "Items", "", new { @class = "tx-wht" })
                </div>
            </td>

            <td>
                <div class="dropdown">
                    <span style="color:aliceblue">Generate reports</span>
                    <div class="dropdown-content">
                        <p>@Html.ActionLink("List of customers", "ListOfCustomer", "Admin")</p>
                        <p>@Html.ActionLink("List of items", "ListOfItems", "Admin")</p>
                        <p>@Html.ActionLink("List of order", "ListOfOreders", "Admin")</p>

                    </div>
                </div>
            </td>
            <td>
                <div style="padding:10px;">
                    @Html.ActionLink("Log out", "Index", "Main", "", new { @class = "tx-wht" })
                </div>
            </td>
        </tr>
    </table>
</div>

<br />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>User</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.userName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.userName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.userName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.firstName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.firstName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.firstName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.lastName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.lastName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.lastName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.age, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.age, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.age, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.confirmPassword, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.confirmPassword, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.confirmPassword, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-primary" />
        </div>
    </div>
</div>
}

RMS/Views/Admin/Delete.cshtml
@model RMS.Models.User

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>User</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.userName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.userName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to Home", "Home","Admin")
        </div>
    }
</div>

RMS/Views/Admin/Details.cshtml
@model RMS.Models.User

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>User</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.password)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.userName }) |
    @Html.ActionLink("Back to Home", "Home","Admin")
</p>

RMS/Views/Admin/DetailsItem.cshtml
@model IEnumerable<RMS.Models.Item>

@{
    ViewBag.Title = "DetailsItem";
}

<div style="margin-left:60%;margin-top:-45px;position:absolute">
    <table>
        <tr>
            <td>
                <div style="padding:10px;">
                    @Html.ActionLink("Home", "AdminHome", "Admin", "", new { @class = "tx-wht" })
                </div>
            </td>
            <td>
                <div style="padding:10px;">
                    @Html.ActionLink("User Control", "Home", "Admin", "", new { @class = "tx-wht" })
                </div>
            </td>
            <td>
                <div style="padding:10px;">
                    @Html.ActionLink("Item control", "Index", "Items", "", new { @class = "tx-wht" })
                </div>
            </td>

            <td>
                <div class="dropdown">
                    <span style="color:aliceblue">Generate reports</span>
                    <div class="dropdown-content">
                        <p>@Html.ActionLink("List of customers", "ListOfCustomer", "Admin")</p>
                        <p>@Html.ActionLink("List of items", "ListOfItems", "Admin")</p>
                        <p>@Html.ActionLink("List of order", "ListOfOreders", "Admin")</p>

                    </div>
                </div>
            </td>
            <td>
                <div style="padding:10px;">
                    @Html.ActionLink("Log out", "Index", "Main", "", new { @class = "tx-wht" })
                </div>
            </td>
        </tr>
    </table>
</div>

<br />

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.itemName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.itemPrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.itemDescription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.itemQnt)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.itemImage)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.itemName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.itemPrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.itemDescription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.itemQnt)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.itemImage)
            </td>
          
        </tr>
    }

</table>

RMS/Views/Admin/Edit.cshtml
@model RMS.Models.User

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>User</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.userName)

    @Html.HiddenFor(model => model.password)

    <div class="form-group">
        @Html.LabelFor(model => model.userName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.userName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.userName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-success" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to Home", "Home","Admin")
</div>

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

RMS/Views/Admin/GenerateReports.cshtml
@{
    ViewBag.Title = "GenerateReports";
}



<div style="margin-left:60%;margin-top:-40px;position:absolute">
    <table>
        <tr>
            <td>
                <div style="padding:10px;">
                    @Html.ActionLink("Home", "AdminHome", "Admin")
                </div>
            </td>
            <td>
                <div style="padding:10px;">
                    @Html.ActionLink("User Control", "Home", "Admin")
                </div>
            </td>
            <td>
                <div style="padding:10px;">
                    @Html.ActionLink("Item control", "Index", "Items")
                </div>
            </td>

            
            <td>
                <div class="dropdown" >
                    <span style="color:aliceblue">Generate reports</span>
                    <div class="dropdown-content">
                        <p>@Html.ActionLink("List of customers", "ListOfCustomer", "Admin")</p>
                        <p>@Html.ActionLink("List of items", "ListOfItems", "Admin")</p>
                        <p>@Html.ActionLink("List of order", "ListOfOreders", "Admin")</p>

                    </div>
                </div>
            </td>
            <td>
                <div style="padding:10px;">
                    @Html.ActionLink("Log out", "Index", "Main")
                </div>
            </td>
        </tr>
    </table>
</div>

<br />

RMS/Views/Admin/Home.cshtml
@model IEnumerable<RMS.Models.User>

@{
    ViewBag.Title = "Home";
}


<div style="margin-left:60%;margin-top:-40px;position:absolute">
    <table>
        <tr>
            <td>
                <div style="padding:10px;">
                    @Html.ActionLink("Home", "AdminHome", "Admin")
                </div>
            </td>
            <td>
                <div style="padding:10px;">
                    @Html.ActionLink("User Control", "Home", "Admin")
                </div>
            </td>
            <td>
                <div style="padding:10px;">
                    @Html.ActionLink("Item control", "Index", "Items")
                </div>
            </td>

            <td>
                <div class="dropdown">
                    <span style="color:aliceblue">Generate reports</span>
                    <div class="dropdown-content">
                        <p>@Html.ActionLink("List of customers", "ListOfCustomer", "Admin")</p>
                        <p>@Html.ActionLink("List of items", "ListOfItems", "Admin")</p>
                        <p>@Html.ActionLink("List of order", "ListOfOreders", "Admin")</p>

                    </div>
                </div>
            </td>
        </tr>
    </table>
</div>

<br />


<p>
    @Html.ActionLink("Create New User", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.userName)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.userName)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.userName }, new { @class = "btn btn-primary" }) |
                @Html.ActionLink("Details", "Details", new { id = item.userName }, new { @class = "btn btn-success" }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.userName }, new { @class = "btn btn-danger" })
            </td>
        </tr>
    }

</table>

RMS/Views/Admin/Index.cshtml
@model RMS.Models.Admin

@{
    ViewBag.Title = "Index";
}

<div style="margin-left:70%;margin-top:-45px;position:absolute">
    <table>
        <tr>
            <td>
                <div style="padding:10px;">
                    @Html.ActionLink("Home", "Index", "Main", "", new { @class = "tx-wht" })
                </div>
            </td>
            <td>
                <div style="padding:10px;">
                    @Html.ActionLink("Admin Login", "Index", "Admin", "", new { @class = "tx-wht" })
                </div>
            </td>
            <td>
                <div>
                    @Html.ActionLink("User Login", "UserLogin", "Users", "", new { @class = "tx-wht" })
                </div>
            </td>
        </tr>
    </table>
</div>

<br />


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal" style="margin-left:35%;margin-top:30px">
        <h4>Admin Login</h4>
      
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.userName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.userName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.userName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.remeberMe, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.remeberMe)
                @Html.ValidationMessageFor(model => model.remeberMe, "")
            </div>
      

        <div class="form-group" style="margin-left:5%">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Login" class="btn btn-primary" />
            </div>
        </div>
    </div>


        </div>
}



<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

RMS/Views/Admin/ListOfCustomer.cshtml
@model IEnumerable<RMS.Models.User>

@{
    ViewBag.Title = "ListOfCustomer";
}


<div style="margin-left:60%;margin-top:-40px;position:absolute">
    <table>
        <tr>
            <td>
                <div style="padding:10px;">
                    @Html.ActionLink("Home", "AdminHome", "Admin", "", new { @class = "tx-wht" })
                </div>
            </td>
            <td>
                <div style="padding:10px;">
                    @Html.ActionLink("User Control", "Home", "Admin", "", new { @class = "tx-wht" })
                </div>
            </td>
            <td>
                <div style="padding:10px;">
                    @Html.ActionLink("Item control", "Index", "Items", "", new { @class = "tx-wht" })
                </div>
            </td>

            <td>
                <div class="dropdown">
                    <span style="color:aliceblue">Generate reports</span>
                    <div class="dropdown-content">
                        <p>@Html.ActionLink("List of customers", "ListOfCustomer", "Admin")</p>
                        <p>@Html.ActionLink("List of items", "ListOfItems", "Admin")</p>
                        <p>@Html.ActionLink("List of order", "ListOfOreders", "Admin")</p>

                    </div>
                </div>
            </td>
            <td>
                <div style="padding:10px;">
                    @Html.ActionLink("Log out", "Index", "Main", "", new { @class = "tx-wht" })
                </div>
            </td>
        </tr>
    </table>
</div>

<br />


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.firstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.lastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.age)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.password)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.firstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.lastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.age)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.password)
            </td>
         
        </tr>
    }

</table>

RMS/Views/Admin/ListOfItems.cshtml
@model IEnumerable<RMS.Models.Item>

@{
    ViewBag.Title = "ListOfItems";
}

<div style="margin-left:60%;margin-top:-40px;position:absolute">
    <table>
        <tr>
            <td>
                <div style="padding:10px;">
                    @Html.ActionLink("Home", "AdminHome", "Admin", "", new { @class = "tx-wht" })
                </div>
            </td>
            <td>
                <div style="padding:10px;">
                    @Html.ActionLink("User Control", "Home", "Admin", "", new { @class = "tx-wht" })
                </div>
            </td>
            <td>
                <div style="padding:10px;">
                    @Html.ActionLink("Item control", "Index", "Items", "", new { @class = "tx-wht" })
                </div>
            </td>

            <td>
                <div class="dropdown">
                    <span style="color:aliceblue">Generate reports</span>
                    <div class="dropdown-content">
                        <p>@Html.ActionLink("List of customers", "ListOfCustomer", "Admin")</p>
                        <p>@Html.ActionLink("List of items", "ListOfItems", "Admin")</p>
                        <p>@Html.ActionLink("List of order", "ListOfOreders", "Admin")</p>

                    </div>
                </div>
            </td>
            <td>
                <div style="padding:10px;">
                    @Html.ActionLink("Log out", "Index", "Main", "", new { @class = "tx-wht" })
                </div>
            </td>
        </tr>
    </table>
</div>

<br />


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.itemName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.itemPrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.itemDescription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.itemQnt)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.itemName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.itemPrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.itemDescription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.itemQnt)
            </td>
            
        </tr>
    }

</table>

RMS/Views/Admin/ListOfOreders.cshtml
@model IEnumerable<RMS.Models.Order>

@{
    ViewBag.Title = "ListOfOreders";
}


<div style="margin-left:60%;margin-top:-40px;position:absolute">
    <table>
        <tr>
            <td>
                <div style="padding:10px;">
                    @Html.ActionLink("Home", "AdminHome", "Admin", "", new { @class = "tx-wht" })
                </div>
            </td>
            <td>
                <div style="padding:10px;">
                    @Html.ActionLink("User Control", "Home", "Admin", "", new { @class = "tx-wht" })
                </div>
            </td>
            <td>
                <div style="padding:10px;">
                    @Html.ActionLink("Item control", "Index", "Items", "", new { @class = "tx-wht" })
                </div>
            </td>

            <td>
                <div class="dropdown">
                    <span style="color:aliceblue">Generate reports</span>
                    <div class="dropdown-content">
                        <p>@Html.ActionLink("List of customers", "ListOfCustomer", "Admin")</p>
                        <p>@Html.ActionLink("List of items", "ListOfItems", "Admin")</p>
                        <p>@Html.ActionLink("List of order", "ListOfOreders", "Admin")</p>

                    </div>
                </div>
            </td>
            <td>
                <div style="padding:10px;">
                    @Html.ActionLink("Log out", "Index", "Main", "", new { @class = "tx-wht" })
                </div>
            </td>
        </tr>
    </table>
</div>

<br />
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.customerName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CustomerAddress)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.userName)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.customerName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CustomerAddress)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.userName)
            </td>
            
        </tr>
    }

</table>