RMS/Models/Cart.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Drawing;
using System.Linq;
using System.Web;

namespace RMS.Models
{
    public class Cart
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public string itemId { get; set; }
        public string userID { get; set; }
       
       
    }
}

RMS/Controllers/CartsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RMS.Data;
using RMS.Models;

namespace RMS.Controllers
{
    public class CartsController : Controller
    {
        private Context db = new Context();

        // GET: Carts
        public ActionResult Index()
        {
            string id = (string)Session["userName"];

            var ob = db.cartDB.SqlQuery("select * from Carts where userID =@id", new SqlParameter("@id", id));
            return View(ob.ToList());
        }

        // GET: Carts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cart cart = db.cartDB.Find(id);
            if (cart == null)
            {
                return HttpNotFound();
            }
            return View(cart);
        }

        // GET: Carts/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Carts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Cart cart)
        {
            if (ModelState.IsValid)
            {
                cart.userID = (string)Session["userName"];
                db.cartDB.Add(cart);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(cart);
        }

        // GET: Carts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cart cart = db.cartDB.Find(id);
            if (cart == null)
            {
                return HttpNotFound();
            }
            return View(cart);
        }

        // POST: Carts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,itemId,userID")] Cart cart)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cart).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(cart);
        }

        // GET: Carts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cart cart = db.cartDB.Find(id);
            if (cart == null)
            {
                return HttpNotFound();
            }
            return View(cart);
        }

        // POST: Carts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Cart cart = db.cartDB.Find(id);
            db.cartDB.Remove(cart);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RMS/Controllers/MainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RMS.Controllers
{
    public class MainController : Controller
    {
        // GET: Main
        public ActionResult Index()
        {


            return View();
        }
    }
}

RMS/Controllers/PaymentDetailsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RMS.Data;
using RMS.Models;

namespace RMS.Controllers
{
    public class PaymentDetailsController : Controller
    {
        private Context db = new Context();

        // GET: PaymentDetails
        public ActionResult Index()
        {
            string id = (string)Session["userName"];
            var ob = db.PaymentDetails.SqlQuery("select * from PaymentDetails where userName=@id", new SqlParameter("@id", id));
            return View(ob.ToList());
        }

        // GET: PaymentDetails/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PaymentDetails paymentDetails = db.PaymentDetails.Find(id);
            if (paymentDetails == null)
            {
                return HttpNotFound();
            }
            return View(paymentDetails);
        }

        // GET: PaymentDetails/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PaymentDetails/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PaymentDetails paymentDetails)
        {
            if (ModelState.IsValid)
            {
                Session["cuName"] = paymentDetails.customerName;
                Session["cuAddress"] = paymentDetails.CustomerAddress;

                string useName = (string)Session["userName"];

                paymentDetails.userName = useName;

                db.PaymentDetails.Add(paymentDetails);
                db.SaveChanges();

                
                return RedirectToAction("Index");
            }

            return View(paymentDetails);
        }

        // GET: PaymentDetails/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PaymentDetails paymentDetails = db.PaymentDetails.Find(id);
            if (paymentDetails == null)
            {
                return HttpNotFound();
            }
            return View(paymentDetails);
        }

        // POST: PaymentDetails/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,customerName,CustomerAddress")] PaymentDetails paymentDetails)
        {
            if (ModelState.IsValid)
            {
                db.Entry(paymentDetails).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(paymentDetails);
        }

        // GET: PaymentDetails/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PaymentDetails paymentDetails = db.PaymentDetails.Find(id);
            if (paymentDetails == null)
            {
                return HttpNotFound();
            }
            return View(paymentDetails);
        }

        // POST: PaymentDetails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            PaymentDetails paymentDetails = db.PaymentDetails.Find(id);
            db.PaymentDetails.Remove(paymentDetails);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


        //generate Order
        public ActionResult GenarateOrders(int ? id)
        {
            if (Request.IsAuthenticated)
            {
                PaymentDetails ob = db.PaymentDetails.Find(id);

                string userName = (string)Session["userName"];
                Session["cuName"] = ob.customerName;
                Session["cuAddress"] = ob.CustomerAddress;

                Order ob2 = new Order();
                ob2.customerName= ob.customerName; ;
                ob2.CustomerAddress= ob.CustomerAddress;
                ob2.userName = userName;

                db.orderDB.Add(ob2);
                db.SaveChanges();

                return View();
            }
            else
            {
                return RedirectToAction("UserLogin", "Users");
            }

        }

    }
}

RMS/Views/Carts/Create.cshtml
@model RMS.Models.Cart

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Cart</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.itemId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.itemId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.itemId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.userID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.userID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.userID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

RMS/Views/Carts/Delete.cshtml
@model RMS.Models.Cart

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Cart</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.itemId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.itemId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.userID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.userID)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

RMS/Views/Carts/Details.cshtml
@model RMS.Models.Cart

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Cart</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.itemId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.itemId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.userID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.userID)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

RMS/Views/Carts/Edit.cshtml
@model RMS.Models.Cart

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Cart</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.itemId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.itemId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.itemId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.userID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.userID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.userID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

RMS/Views/Carts/Index.cshtml
@model IEnumerable<RMS.Models.Cart>

@{
    ViewBag.Title = "Index";
}


<div style="margin-left:70%;margin-top:-50px;position:absolute">
    <table>
        <tr>
            <td>
                <div style="padding:10px"> @Html.ActionLink("Home", "UserHome","Users") </div>
            </td>
            <td>
                <div style="padding:10px"> @Html.ActionLink("Go to profile", "UserProfile","Users") </div>
            </td>
            <td>
                <div style="padding:10px">  @Html.ActionLink("Cart", "Index","Carts") </div>
            </td>

            <td>
                <div style="padding:10px;">
                    @Html.ActionLink("Log out", "Index", "Main")
                </div>
            </td>

        </tr>
    </table>
</div>

<br />


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.itemId)
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.itemId)
            </td>

            <td>
                @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "btn btn-danger" })
            </td>
        </tr>
    }

</table>

<div style="float:right;margin-top:20px">
    <p>
        @Html.ActionLink("Placed to order", "Index", "PaymentDetails","", new { @class = "btn btn-success" })
    </p>
</div>

<hr />